# .github/workflows/terraform.yml
# This workflow manually deploys the infrastructure using Terraform.
name: CD - Deploy with Terraform

on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI
    inputs:
      image_tag:
        description: 'Image tag to deploy (e.g., commit SHA from the CI build)'
        required: true
        # The default value was removed as it cannot use the github context.

jobs:
  terraform-deploy:
    name: Deploy to AWS via Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0 # Specify a Terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Mumbai

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color \
            -var="image_tag=${{ github.event.inputs.image_tag }}" \
            -var="ecr_repository_url=${{ secrets.ECR_REPOSITORY_URL }}" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -out=tfplan
        continue-on-error: true # Allow plan to show diffs without failing the workflow

      - name: Terraform Apply
        id: apply
        # Only run apply if the workflow was manually triggered
        if: github.event_name == 'workflow_dispatch'
        run: |
          terraform apply -auto-approve tfplan

