# .github/workflows/terraform.yml

name: CD - Deploy to EC2 with Terraform

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag (commit SHA) to deploy'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        # === FIX IS HERE: Add the env block to the 'plan' step ===
        env:
          TF_VAR_app_keys: ${{ secrets.STRAPI_APP_KEYS }}
          TF_VAR_api_token_salt: ${{ secrets.STRAPI_API_TOKEN_SALT }}
          TF_VAR_admin_jwt_secret: ${{ secrets.STRAPI_ADMIN_JWT_SECRET }}
          TF_VAR_transfer_token_salt: ${{ secrets.STRAPI_TRANSFER_TOKEN_SALT }}
        run: terraform plan -var="strapi_image_tag=${{ github.event.inputs.image_tag }}" -no-color

      - name: Terraform Apply
        id: apply
        # The env block must be here as well
        env:
          TF_VAR_app_keys: ${{ secrets.STRAPI_APP_KEYS }}
          TF_VAR_api_token_salt: ${{ secrets.STRAPI_API_TOKEN_SALT }}
          TF_VAR_admin_jwt_secret: ${{ secrets.STRAPI_ADMIN_JWT_SECRET }}
          TF_VAR_transfer_token_salt: ${{ secrets.STRAPI_TRANSFER_TOKEN_SALT }}
        run: terraform apply -auto-approve -var="strapi_image_tag=${{ github.event.inputs.image_tag }}"

